title: 백엔드 개발자 수현's blog
description: >-
  백엔드 개발자 수현 <br>
  기록들.
url: "http://i960107.github.io"
github: i960107
email: i960107@naver.com
google_analytics: <YOUR UA TOKEN>

exclude: [ README.md, Gemfile, Gemfile.lock ]

kramdown:
  syntax_highlighter: rouge

comments:
  enabled: true
  repo: ChemistryX/hyde-comments
  issue-term: pathname

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /posts/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title

